--- 
version: 2
jobs:
  build:
    working_directory: ~/angular8
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: install-dependencies
          command:  npm install @angular/cli@8.3.6
      - run:
          name: install-dependencies
          command:  npm audit fix --force
      - run:
          name: angular-build
          command: npm ng -- build
      - store_artifacts:
          path: artifact.xml
          prefix: build
      
