defaults: &defaults
  working_directory: ~/angular8
  docker:
    - image: cyber4all/circleci-aws:node-alpine

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install Dependencies
          command: npm install @angular/cli@8.3.6
      - run:
          name: Install Dependencies
          command: npm audit fix --force    
      - run:
          name: Build Application
          command: npm ng build 
      - persist_to_workspace: 
          root: dist
          paths: 
            - ./
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Unit Tests
          command: npm run test:unit
