version: 2
jobs:
   build:
     working_directory: ~/angular8
     docker:
       - image: circleci/node:latest 

     steps:
       - checkout
       - restore_cache:
           key: sudo dependency-cache-{{ checksum "package-lock.json" }}
       - run:
           name: Install npm
           command: npm install
       - save_cache:
           key: sudo dependency-cache-{{ checksum "package-lock.json" }}
           paths:
             - node_modules
       - run:
           name: Install Dependencies
           command: npm install @angular/cli@8.3.20
      # - run:
      #     name: audit fix
       #    command: npm audit fix --force
       - run:
           name: Build Application
           command: npm run build
       - run:
           name: Zip Application
           command: zip artifact.zip dist appspec.yml
       
       - persist_to_workspace: 
           root: dist
           paths: 
             - ./   
     #  - run: 
       #    name: compress artifacts
       #    command: tar -cvf myartifact.tar dist  
       - save_cache:
                key: zip-artifact.zip-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - ./
   upload_artifacts:
     docker:
       - image: circleci/node:latest
     working_directory: ~/mynewrepo
     steps: 
       - checkout 
       - restore_cache:
                key: zip-artifact.zip-
       - run:
           name: set identity 
           command: |
               git config --global user.email "suryawal.deepali@gmail.com"
               git config --global user.name "deep2131"
               #git config --global push.followTags true
       - run:
           name: upload artifact
           command: |
               git clone git@github.com:deep2131/mynewrepo.git
               cd mynewrepo
               ls -ltr
               git status
               cp ./artifact.zip .
               git add artifact.zip
               git commit -m "artifact"
               git push --force origin master
               
           
       
workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - upload_artifacts:
          requires:
            - build
           
  
