defaults: &defaults
  working_directory: ~/angular8
  docker:
    - image: circleci/node:latest 

version: 2
jobs:
   build:
     <<: *defaults
     steps:
       - checkout
       - restore_cache:
           key: sudo dependency-cache-{{ checksum "package-lock.json" }}
       - run:
           name: Install npm
           command: npm install
       - save_cache:
           key: sudo dependency-cache-{{ checksum "package-lock.json" }}
           paths:
             - node_modules
       - run:
           name: Install Dependencies
           command: npm install @angular/cli@8.3.20
       - run:
           name: audit fix
           command: npm audit fix --force
       - run:
           name: Build Application
           command: npm run build
           
       - persist_to_workspace: 
           root: dist
           paths: 
             - ./
       - run: 
           name: compress artifacts
           command: tar -cvf myartifact.tar dist  
       - run:
           name: upload artifact
           command: git push --force origin master myartifact.tar 
            
            #myartifacts --build-name= demo --build-number=$CIRCLE_BUILD_NUM
           
           
    # ./jfrog rt u <path/to/artifact> <artifactory_repo_name> --build-name=<name_you_give_to_build> --build-number=$CIRCLE_BUILD_NUM


       
workflows:
   version: 2
   build-deploy:
     jobs:
       - build
      #- deploy:
        #  requires:
         #   - build
           
  
