defaults: &defaults
  working_directory: ~/angular8
  docker:
    - image: circleci/node:latest 

version: 2
jobs:
   build:
     <<: *defaults
     steps:
       - checkout
       - restore_cache:
           key: sudo dependency-cache-{{ checksum "package-lock.json" }}
       - run:
           name: Install npm
           command: npm install
       - save_cache:
           key: sudo dependency-cache-{{ checksum "package-lock.json" }}
           paths:
             - node_modules
       - run:
           name: Install Dependencies
           command: npm install @angular/cli@8.3.20
       - run:
           name: audit fix
           command: npm audit fix --force
       - run:
           name: Build Application
           command: npm run build
           
       - persist_to_workspace: 
           root: dist
           paths: 
             - ./
       - run: 
           name: compress artifacts
           command: tar -cvf myartifact.tar dist  
      # - store_artifacts:
       #    path: myartifact.tar
       #    destination: Build
           
     
       - run:
           name: set identity 
           command: |
               git config --global user.email "suryawal.deepali.com"
               git config --global user.name "deep2131"
               git config --global push.followTags true
       - run:
           name: upload artifact
           command: |
               git add myartifact.tar
               git commit -m "artifact"
               git push origin master
               git pull git@github.com:deep2131/angular8.git
               cd myartifact.tar
               git remote rm origin
               mkdir dir1
               mv * dir1
               git add .
               git commit
               git clone git@github.com:deep2131/Artifacts.git
               cd artifacts
               git remote add myartifact.tar
               git pull git@github.com:deep2131/angular8.git
               git remote rm git@github.com:deep2131/angular8.git
               git push --force origin master
           
           
       
workflows:
   version: 2
   build-deploy:
     jobs:
       - build
      #- deploy:
        #  requires:
         #   - build
           
  
