defaults: &defaults
  working_directory: ~/angular8
  docker:
    - image: cyber4all/circleci-aws:node-alpine

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Dependencies
          command: npm install @angular/cli@8.3.6
          
      - run:
          name: 
          command: npm 'package-lock.jason' --key value
      - run:
          name: Install Dependencies
          command: npm audit fix --force    
      - run:
          name: Build Application
          command: npm ng build --prod --no-progress
      - persist_to_workspace: 
          root: dist
          paths: 
            - ./
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Unit Tests
          command: npm run test:unit
