version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
jobs:
   build:
     branches:
      only:
        - testing
     docker:
       - image: circleci/node:12.2.0
     working_directory: ~/angular8

      steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build            
      - aws-ecr/build-and-push-image:
          requires:
            - build
          account-url: AWS_ACCOUNT_ID
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          repo: myrepo
          dockerfile: "Dockerfile"
          region: AWS_REGION
