defaults: &defaults
  working_directory: ~/angular8
  docker:
    - image: cyber4all/circleci-aws:node-alpine

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: yarn ng build --prod --no-progress
      - persist_to_workspace: 
          root: dist
          paths: 
            - ./
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Unit Tests
          command: npm run test:unit
