defaults: &defaults
  working_directory: ~/angular8
  docker:
    - image: circleci/node:latest 

version: 2
jobs:
   build:
     steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: sudo dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: sudo dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install Dependencies
          command: npm install @angular/cli@8.3.20
      - run:
          name: audit fix
          command: npm audit fix --force
      - run:
          name: Build Application
          command: npm run build
           
      - persist_to_workspace: 
          root: dist
          paths: 
            - ./
   test:
   requires:
      - build
     steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Unit Tests
          command: npm run test:unit
  deploy:
    machine:
      enabled: true
    working_directory: ~/angular8
    steps:
       - run:
          name: Deploy
          command: 'aws s3 sync ${./dist}/ s3://${angular-s3-bucket} --region ap-south-1'       
          
workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
          workspace: .
          artifacts: dist
          bucket: angular-s3-bucket
          
   
 
       
